name: solid_social
description: Solid Social App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.1
  firebase_dynamic_links: ^5.0.6
  cloud_functions: ^4.0.5


  # Stream chat
  stream_chat_flutter: ^5.1.0

  # Agora
  agora_rtc_engine: ^6.1.0
  agora_uikit: ^1.1.0
  agora_rtm: ^1.5.0
  
  # Caching
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #Utils
  image_picker: ^0.8.6
  intl: ^0.17.0
  photo_manager: ^2.5.1+1
  http: ^0.13.5

  # Social Auth
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  flutter_facebook_auth: ^5.0.6

  # UI
  cupertino_icons: ^1.0.5
  flutter_emoji: ^2.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  iconsax: ^0.0.8
  timeago: ^3.3.0
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  story_view: ^0.14.0

  # State Management
  provider: ^6.0.4
  state_notifier: ^0.7.2+1

  # Generators
  equatable: ^2.0.5
  json_serializable: ^6.5.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
  # Helpers
  freezed: ^2.2.1
  build_runner: ^2.3.2
  import_sorter: ^4.6.0


dependency_overrides:
  share_plus: ^4.5.0
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/emojis/
    - assets/launcher_icons/
    - assets/custom_icons/
    - assets/sample_images/
    - assets/logos/
    - assets/logos/signup/whitelogo2.png
    - assets/backgrounds/login_signup/
    - assets/logos/svg/
    - assets/custom_icons/bottom_nav/outlined/
    - assets/sample_images/avatars/
    - assets/backgrounds/community/
    - assets/backgrounds/cards/
    - assets/custom_icons/bottom_nav/bold/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher_icons/icon1024.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: 'assets/launcher_icons/icon1024.png'
